// SPDX-License-Identifier: BUSL-1.1
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.6.6. SEE SOURCE BELOW. !!
pragma solidity >=0.8.19 <0.9.0;

interface IFactory {
    event Deployed(address indexed implementation, address indexed proxy);

    function deploy(
        address implementation,
        bytes memory initializer
    ) external payable returns (address proxy);
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"type":"event","anonymous":false,"inputs":[{"name":"implementation","internalType":"address","type":"address","indexed":true},{"name":"proxy","internalType":"address","type":"address","indexed":true}],"name":"Deployed"},{"stateMutability":"payable","type":"function","inputs":[{"name":"implementation","internalType":"address","type":"address"},{"name":"initializer","internalType":"bytes","type":"bytes"}],"name":"deploy","outputs":[{"name":"proxy","internalType":"address","type":"address"}]}]
*/
